version: '3.7'
services:
  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=myPw123
      - POSTGRES_DB=app
    volumes:
      - ./data/:/var/lib/postgresql
    ports:
      - '5432:5432'

